version: '2'
services:
  connect:
    image: debezium/connect:1.6
    container_name: connect
    ports:
      - 8083:8083
    environment:
      - GROUP_ID=28786_1
      - CONFIG_STORAGE_TOPIC=28786_hisgateway_connect_configs
      - OFFSET_STORAGE_TOPIC=28786_hisgateway_connect_offsets
      - STATUS_STORAGE_TOPIC=28786_hisgateway_connect_statuses
      - CONNECT_SSL_TRUSTSTORE_LOCATION=/var/private/ssl/kafka.client.28786.truststore.jks
      - CONNECT_PRODUCER_SSL_TRUSTSTORE_LOCATION=/var/private/ssl/kafka.client.28786.truststore.jks
      - CONNECT_SSL_KEYSTORE_LOCATION=/var/private/ssl/kafka.client.28786.keystore.jks
      - CONNECT_PRODUCER_SSL_KEYSTORE_LOCATION=/var/private/ssl/kafka.client.28786.keystore.jks
      - CONNECT_PRODUCER_SSL_TRUSTSTORE_PASSWORD=WQBo4xWTMJaMGVg7Ye1g
      - CONNECT_PRODUCER_SSL_KEYSTORE_PASSWORD=WQBo4xWTMJaMGVg7Ye1g
      - CONNECT_SSL_TRUSTSTORE_PASSWORD=WQBo4xWTMJaMGVg7Ye1g
      - CONNECT_SSL_KEYSTORE_PASSWORD=WQBo4xWTMJaMGVg7Ye1g
      - CONNECT_SSL_KEY_PASSWORD=WQBo4xWTMJaMGVg7Ye1g
      - CONNECT_PRODUCER_SSL_KEY_PASSWORD=WQBo4xWTMJaMGVg7Ye1g
      - BOOTSTRAP_SERVERS=broker1.gateway.moph.go.th:9093,broker2.gateway.moph.go.th:9093,broker3.gateway.moph.go.th:9093
      - CONNECT_PRODUCER_BOOTSTRAP_SERVERS=broker1.gateway.moph.go.th:9093,broker2.gateway.moph.go.th:9093,broker3.gateway.moph.go.th:9093
      - CONNECT_SECURITY_PROTOCOL=SSL
      - CONNECT_PRODUCER_SECURITY_PROTOCOL=SSL
      - CONNECT_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM= 
      - CONNECT_PRODUCER_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM= 
      - CONNECT_MAX_REQUEST_SIZE=104857600
      - CONNECT_CONNECTOR_CLIENT_CONFIG_OVERRIDE_POLICY=All
    volumes: 
      - ./cert:/var/private/ssl
    networks:
      gw-network:
        ipv4_address: 192.168.4.5
  hisgateway-web:
    image: mophos/hisgateway-client-web
    container_name: hisgateway-web
    restart: always
    networks:
      gw-network:
        ipv4_address: 192.168.4.3
  hisgateway-api:
    image: mophos/hisgateway-client-api
    restart: always
    container_name: hisgateway-api
    environment: 
      - KAFKA_CONNECT_ENDPOINT=http://192.168.4.5:8083
      - ICTPORTAL_ENDPOINT=https://oauth.moph.go.th/v1/login
      - SECRET_KEY=123456
    links: 
      - connect
    pid: "host"
    networks:
      gw-network:
        ipv4_address: 192.168.4.4
  hisgateway-mqtt:
    image: mophos/hisgateway-client-mqtt
    restart: always
    container_name: hisgateway-mqtt
    environment: 
      - HOSPCODE=28786
    pid: "host"
    networks:
      gw-network:
        ipv4_address: 192.168.4.6
  nginx:
    image: nginx:1.13.0-alpine
    container_name: nginx
    restart: always
    ports: 
    - "80:80"
    volumes: 
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      gw-network:
        ipv4_address: 192.168.4.2
networks:
  gw-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.4.0/24
